# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.0'
prepare_react_native_project!

flipper_config = ENV['NO_FLIPPER'] == '1' ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

target 'LxMusicMobile' do
  config = use_native_modules!
  react_native_path = config[:reactNativePath]

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :flipper_configuration => flipper_config,
    :app_transport_security_enabled => true
  )
end

target 'LxMusicMobileTests' do
  inherit! :complete
end

post_install do |installer|
  react_native_post_install(
    installer,
    config[:reactNativePath],
    mac_catalyst_enabled: false
  )
end
